apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyz-app
  template:
    metadata:
      labels:
        app: xyz-app
    spec:
      containers:
      - name: xyz-app
        image: your-docker-image
        ports:
        - containerPort: 5000
